version: "3.7"
services: 
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMT_ERLANG_COOKIE: 'secret cookie there'
    volumes:
      - ./db-data:/var/lib/rabbitmq
    ports:
      - 15672:15672